version: '2'
services:
  elasticsearch:
    image: elasticsearch:2.4
    ports:
      - "9200:9200"
    volumes:
      - elastic:/usr/share/elasticsearch/data

  postgres:
    image: postgres:9.5
    environment:
      POSTGRES_PASSWORD: fpp
      POSTGRES_USER: fpp
      POSTGRES_DB: fpp
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
  elastic:
