version: '2'
services:
  elasticsearch:
    image: elasticsearch:2.4
    volumes:
      - elastic:/usr/share/elasticsearch/data

  smtp:
    image: 'djfarrelly/maildev:latest'
    command: 'bin/maildev --web 3080 --smtp 1025 --incoming-user smtp --incoming-pass smtp'
    ports:
      - '3080:3080'

  db:
    image: postgres:9.5
    environment:
      POSTGRES_USER: root
    volumes:
      - db:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    env_file: dev.env
    pid: host
    working_dir: /src
    depends_on:
      - db
      - smtp
      - elasticsearch
    volumes:
      - .:/src
      - bundle:/usr/local/bundle
      - elm-stuff:/src/elm-stuff
    ports:
      - "3000:3000"
    command: /bin/sh -c './bin/update && bundle exec ./bin/rails s -b 0.0.0.0'

volumes:
  db:
  elastic:
  bundle:
  elm-stuff:

