version: '2'
services:
  elasticsearch:
    image: elasticsearch:2.4
    ports:
      - "9200:9200"
    volumes:
      - elastic:/usr/share/elasticsearch/data

  smtp:
    image: 'djfarrelly/maildev:latest'
    command: 'bin/maildev --web 3080 --smtp 1025 --incoming-user smtp --incoming-pass smtp'
    ports:
      - '3080:3080'
      - '1025:1025'

  postgres:
    image: postgres:9.5
    environment:
      POSTGRES_PASSWORD: fpp
      POSTGRES_USER: fpp
      POSTGRES_DB: fpp
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
  elastic:
