FROM ruby:2.3.8

RUN \
  echo "deb http://archive.ubuntu.com/ubuntu/ xenial main universe" > /etc/apt/sources.list && \
  echo "deb http://archive.ubuntu.com/ubuntu/ xenial-updates main universe" >> /etc/apt/sources.list \
  apt-get update && \
  apt-get install -y gnupg && \
  apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 40976EAF437D05B5 3B4FE6ACC0B21F32 && \
  apt-get update && \
  # node
  curl -sL https://deb.nodesource.com/setup_8.x | bash - && \
  apt-get install -y nodejs 
  #&& \
  # elm
  # npm install -g elm@0.17.1 --unsafe-perm=true --allow-root && \

# Download the Elm binary release
#RUN curl -L -o /tmp/elm.gz https://github.com/lydell/elm-old-binaries/releases/download/main/0.17.1-linux-x64.tar.gz

#RUN tar -zxvf /tmp/elm.tar.gz > /usr/local/bin/elm
RUN cd /tmp && \
    curl -L https://github.com/lydell/elm-old-binaries/releases/download/main/0.17.1-linux-x64.tar.gz | tar zx && \
    mv dist_binaries/* /usr/local/bin && \
    rm -rf dist_binaries

# Make the Elm binaries executable
RUN chmod +x /usr/local/bin/elm*

# clean
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
