version: 0.3.0
report_email_to: "example@example.com"
report_email_from: "do-not-reply@facilitypublicportal.com"
smtp_settings: {}
  # address: 127.0.0.1
  # port: 1025
  # user_name: smtp
  # password: smtp
initial_position:
  lat: 16
  lng: 7
map_bounds:
  top: 22
  left: -2
  bottom: 10
  right: 15
map_zoom:
  min: 6
  max: 18
  default: 7
user_position: fake
mapbox_id: "mapbox/streets-v9"
mapbox_token: "pk.eyJ1IjoibWZyIiwiYSI6ImNpdDBieTFhdzBsZ3gyemtoMmlpODAzYTEifQ.S9MV3eZjN39ZXh_G5_2gWQ"
default_locale: en
locales:
  en: English
