version: 0.4.0
report_email_to: "example@example.com"
report_email_from: "do-not-reply@facilitypublicportal.com"
smtp_settings: {}
  # address: 127.0.0.1
  # port: 1025
  # user_name: smtp
  # password: smtp
initial_position:
  lat: 8.979787
  lng: 38.758917
map_bounds:
  top: 37.000000
  left: -17.000000
  bottom: -35.000000
  right: 51.000000
map_zoom:
  min: 2
  max: 18
  default: 13
user_position: fake
mapbox_id: "mapbox/streets-v9"
mapbox_token: "pk.eyJ1IjoibWZyIiwiYSI6ImNpdDBieTFhdzBsZ3gyemtoMmlpODAzYTEifQ.S9MV3eZjN39ZXh_G5_2gWQ"
facility_photos: true
default_locale: en
input_dir: data/input
locales:
  en: English
