report_email_to: "example@example.com"
report_email_from: "do-not-reply@facilitypublicportal.com"
smtp_settings:
  address: 127.0.0.1
  port: 1025
  user_name: smtp
  password: smtp
initial_position:
  lat: 8.979787
  lng: 38.758917
map_bounds:
  top: 16.191368
  left: 28.774925
  bottom: 0.283346
  right: 52.637229
user_position: fake
mapbox_id: "mapbox/streets-v9"
mapbox_token: "pk.eyJ1IjoibWZyIiwiYSI6ImNpdDBieTFhdzBsZ3gyemtoMmlpODAzYTEifQ.S9MV3eZjN39ZXh_G5_2gWQ"
default_locale: en
locales:
  en: English
