report_email_to: "example@example.com"
report_email_from: "do-not-reply@facilitypublicportal.com"
smtp_settings:
  address: 127.0.0.1
  port: 1025
  user_name: smtp
  password: smtp
initial_position:
  lat: 8.979787
  lng: 38.758917
user_position: fake
